### ISSUE TITLE
 Error: Cannot find certificate MyCertificate , all certs

### ISSUE THREAD

**Issue by biloo-dev** [nklayman/vue-cli-plugin-electron-builder#1023]
**Describe the bug**
  
**hello everyone i had this problem when i tried to signed my application with certificate.pfx** 
![2020-09-07_173009](https://user-images.githubusercontent.com/37638323/92415556-635e7080-f151-11ea-8bac-915528ce83d2.png)
 
![2020-09-07_173446](https://user-images.githubusercontent.com/37638323/92415562-66f1f780-f151-11ea-876a-828b428b3080.png)

**Comment by nklayman** [comment]
The path is invalid because it is using a source map that points to the original source of that npm package. The real issue is that you are setting `certificateSubjectName` which is only supposed to be set if you are using a EV certificate, which is a physical usb drive. It seems like you mean to use the `.pfx` file instead. Try removing the `certificateSubjectName` config and see if it works. See [the electron builder docs](https://www.electron.build/code-signing) for more details.

P.S. The certificate password is visible in the image you uploaded. I can delete this issue if you want it hidden, although it may have been archived elsewhere. Be careful what you post on the internet.
