### ISSUE TITLE
Uncaught TypeError: Cannot set property 'available_wifi' of undefined

### ISSUE THREAD

**Issue by Hariprabu94** [nklayman/vue-cli-plugin-electron-builder#1045]
```
<template>
  <div class="home">
     <div class="registration">
     <div class="wifi_pad" v-for="value in available_wifi" v-bind:key="value.mac">
    {{ value.ssid }}
    </div>
     </div>
  </div>
</template>
<script>
import wifi from 'node-wifi'
export default{
  data(){
    return {
available_wifi:"",
    }
  },
  mounted(){
    wifi.init({
  iface: null
});
wifi.scan(function(err, networks) {
  if (err) {
    console.log(err);
  } else {
   
   console.log(networks);
     this.available_wifi = networks;
  
  }
});
  },
  }
}
</script>

```
In this case my console log was logged successfully. But getting error while access data to vue template.
I attached error screenshot.
Kindly assist. thank you
![Screenshot-20200916073047-538x165](https://user-images.githubusercontent.com/56619957/93283952-3106e000-f7ef-11ea-8398-b906b32b67ae.png)

**Comment by nklayman** [comment]
This issue doesn't have anything to do with this plugin, it will fail in any vue application. The issue is that the anonymous function passed to `wifi.scan` has it's own `this` binding. You need to replace it with an ES6 arrow function, which binds to the parent `this`. See [this page](https://javascript.info/arrow-functions) for more details about arrow functions and how they have a different `this` binding.
