### ISSUE TITLE
Run production version without building complete, bundled app with electron-builder

### ISSUE THREAD

**Issue by ylieder** [nklayman/vue-cli-plugin-electron-builder#1057]
Currently, there are only the run script options `electron:build` and `electron:serve`. But sometimes, it would be nice to test the production version without building the complete app with electron-builder on every change.

It would be great to have a third option like `electron:prod`, which bundles the production version with Webpack and executes the electron binary, but doesn't build the complete app with electron-builder.

**Comment by nklayman** [comment]
Electron builder executes extremely quickly if you don't create any installers. If you run `yarn electron:build --dir` (or `npm run electron:build -- --dir`), it will just create the binary in `dist_electron/PLATFORM-unpacked/APPNAME(.exe)`. The electron builder phase should only take a few seconds in this case and then you can immediately execute the binary. This will also be closer to the finished app compared to just launching the electron binary. You can also set the `NODE_ENV` env var to `production` during `electron:serve`, which will use the prod webpack config and environment variables.

I've used the first solution for myself hundreds of times, and it is very quick and easy. Because of this, I don't think that it is worth it to add a whole new command just to save a couple keystrokes and a few seconds of time. Hopefully the solutions I mentioned are satisfactory for you as well.

**Comment by ylieder** [comment]
Exactly what I was looking for! Thanks!
