### ISSUE TITLE
 Vue CLI build failed. Please resolve any issues with your build and try again.

### ISSUE THREAD

**Issue by Nisthar** [nklayman/vue-cli-plugin-electron-builder#1076]
I am getting ` Vue CLI build failed. Please resolve any issues with your build and try again.` when i run the `vue-cli-service electron:build` command.

The serve command is working fine. 

If i run the command `npm run build` it gives me the error 
```
Error: CSS minification error: Expected a pseudo-class or pseudo-element.. File: css/app.a1ff64ba.css
```

**Comment by Nisthar** [comment]
It used to work fine before.

**Comment by fspoettel** [comment]
The error message `expected a pseudo-class or pseudo-element` suggests a syntax error with pseudo classes in one of your application's CSS files. Most likely, this is only an issue for the minifier (only run on `build` with vue-cli) which cannot handle the ambivalent syntax.

Maybe you wrote: 
```css
.header :last-child {}
```
instead of:
``` css
.header:last-child {}
```

**Comment by nklayman** [comment]
Thanks @fspoettel for your detailed response :+1:.

@Nisthar Since the error is failing at the Vue CLI build stage, the issue is most defiantly not caused by this plugin. If the posted solution doesn't work for you, open an issue on the vue cli repository. They will probably need reproduction instructions or an example repo to help you, so I suggest including that.

**Comment by Nisthar** [comment]
@fspoettel If there's an error in the application's css files, how is the `npm run serve` command working.

**Comment by fspoettel** [comment]
@Nisthar the error is raised by the minifier. `serve` does not minify your CSS so the minifier is only run on `build`.
Browsers sometimes are more permissive with parsing syntax than build tools are so it's possible that `serve` is perfectly fine while `build ` throws an error.

Sorry I can't help you more here. If you know the git commit where this last worked, maybe try compare what changed in between then and now and try to spot the error.

**Comment by Nisthar** [comment]
I haven't changed my app's css in a long time now. So i don't think its my applications css files. It might be an issue with tailwindcss i guess.

**Comment by Nisthar** [comment]
Is there any way to get more detailed error? This error message is too general

**Comment by fspoettel** [comment]
@Nisthar I don't think this is the correct repo to ask that question. This is not an issue with `vue-cli-plugin-electron-builder`. Your problem seems to originate from the `build` step which is handled by `@vue/cli`. Maybe ask over there or in the Vue.js Discourse forum, they will be better equipped to answer that question in detail.

**Comment by Nisthar** [comment]
Ok, my bad. I found my solution.

**Comment by fsk** [comment]
```
ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.
Waiting for the debugger to disconnect...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meetoz-dsk@0.1.0 electron:build: `vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dsk@0.1.0 electron:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2021-12-27T23_47_37_547Z-debug.log
Waiting for the debugger to disconnect...
```

This is my issue. I didnt see any errors. Just tell me **_'ERROR  Vue CLI build failed. Please resolve any issues with your build and try again.'._** 

How can i fix.? 

And i am using `npm run electron:builder` commant.
