### ISSUE TITLE
Iframe not render on Window Shared Network

### ISSUE THREAD

**Issue by zernonia** [nklayman/vue-cli-plugin-electron-builder#1081]
**Describe the bug**
After executing `npm run electron:build`, I've place the `win_unpacked` in a Shared Network in Window and run the apps. Everything is good but iframe. It doesn't render the content in the iframe. Iframe src is `https://...com`

I've tested the apps on Local Drive ( C:\ ) but no issue rendering it.

**To Reproduce**
1. Run `npm run electron:build`
2. Copy the `win_unpacked` to Shared Network
3. Run application

**Expected behavior**
Iframe to render content without issue.

**For More Clearance**
I've tried using a plain html file (not electron) with the same src link as above and it works flawlessly. I'm confused why the iframe in electron app is not working.

**Comment by nklayman** [comment]
I have no idea why it wouldn't work, and I don't have a shared windows network to test this with, unfortunately. I think this is a problem with electron rather than this plugin, so I'd suggest cloning [this boilerplate repo](https://github.com/electron/electron-quick-start) and adding just the iframe. Move it to the shared drive, and see if it exhibits the same error as the one you built with this plugin. If it does, then the issue is with electron itself and you should open an issue on its repo. If it works fine, let me know and I'll see if I can find a way to test it.
