### ISSUE TITLE
Electron 10 support

### ISSUE THREAD

**Issue by zzmao** [nklayman/vue-cli-plugin-electron-builder#1093]
**Is your feature request related to a problem? Please describe.**
Chromium in Electron 9 are lack of some wasm support. 

**Describe the solution you'd like**
Electron 10 

**Describe alternatives you've considered**

**Additional context**

**Comment by nklayman** [comment]
You can upgrade to Electron 10 manually and it should work fine. The reason I haven't added it to the installation prompts is because Spectron (testing library for Electron) is broken with Electron v10. See this issue for more details: https://github.com/electron-userland/spectron/issues/720. Once that issue is fixed and testing will work then I will add it as an option for the installer.

**Comment by zzmao** [comment]
@nklayman   thanks!
