### ISSUE TITLE
electron:build The dependency of post configuration in dependencies is not complete

### ISSUE THREAD

**Issue by TabCrazy** [nklayman/vue-cli-plugin-electron-builder#1108]
**Describe the bug**

`electron:build` Only part of the dependencies configured in dependencies are in the installation package, such as the 'lighthouse logger' dependency in the screenshot. Without `lighthouse`  and `commander`, the project cannot run normally after installation

**To Reproduce**

`npm run electron:build`

**Expected behavior**

`electron:build` You can configure the dependencies in dependencies and package them into the installation package

**Screenshots**
![image](https://user-images.githubusercontent.com/7017911/97069691-6f6c9780-1604-11eb-838e-a484bb47d60d.png)

**Environment (please complete the following information):**

![image](https://user-images.githubusercontent.com/7017911/97069787-223cf580-1605-11eb-8eb3-1f3a340b7fd1.png)

**Comment by nklayman** [comment]
If you want the dependency to be copied over, you have to mark it as an external. To do so, add this to your `vue.config.js`:

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      externals: ['my-dep']
    }
  }
}
```
Deps aren't copied over by default because it is assumed they are going to be bundled by webpack. Deps that can't be bundled like that have to be listed specially. Try adding your deps to that array and let me know if that works.

**Comment by TabCrazy** [comment]
thank you

**Comment by TabCrazy** [comment]
通过在`vue.config.js` 配置，`externals`, 可以指定builder进安装包的依赖
