### ISSUE TITLE
Test using native modules fails to run with

### ISSUE THREAD

**Issue by ejohnso49** [nklayman/vue-cli-plugin-electron-builder#1114]
**Describe the bug**
When testing with `yarn test:unit` (which I think is running mochapack under the hood), the test fails to run because it is unable to find the binding for the `serialport` native module.

**To Reproduce**
* Add `serialport` as dependency of project
* Add the test below into `tests/unit/`
* Run `yarn test:unit`

`serialport.spec.ts`:
```
import SerialPort from "serialport";
import { expect } from "chai";

describe("Test SerialPort", function() {
  it("Loads the serial port list", async function() {
    const ports = await SerialPort.list();
    expect(ports.length).is.greaterThan(1);
  });
});
```

**Expected behavior**
The test should be able to run and succeed.

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder:
```
module.exports = {
  transpileDependencies: ["vuetify"],
  pluginOptions: {
    electronBuilder: {
      externals: ["serialport"],
      nodeIntegration: false,
      mainProcessFile: "src/core/main.ts",
      rendererProcessFile: "src/ui/main.ts"
    }
  }
};
```

 - terminal output from running `vue info`:
[vue_info.txt](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/5463186/vue_info.txt)

**Additional context**
* As seen in the vue.config.js file I have altered the structure of the application, but I do not believe this would affect the unit test.

Output from `yarn test:unit`:
[test_unit_output.txt](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/5463188/test_unit_output.txt)

`package.json`:
[package.txt](https://github.com/nklayman/vue-cli-plugin-electron-builder/files/5463227/package.txt)

My best guess for the cause is some sort of version mismatch between the Node that Mochapack is using vs the Node that Electron uses and for which electon-builder downloaded the bindings for.

**Comment by nklayman** [comment]
The issue is that `serialport` is a native module, and can't be transpiled by webpack. It should by imported like so:
```js
// eslint-disable-next-line no-undef
const serialport = __non_webpack_require__('serialport')
```

However, there is still an error because of mismatching native module builds. to take care of this, you will have to remove the following line from your `package.json`: `"postinstall": "electron-builder install-app-deps",` and then run `yarn --force` to rebuild serialport to the node version instead of the electron-version. Note that this will prevent native modules from working in electron, but I can't think  of a way to get around this.
