### ISSUE TITLE
Can't call external, unprocessed files from the background script

### ISSUE THREAD

**Issue by avi12** [nklayman/vue-cli-plugin-electron-builder#1123]
**Describe the bug**
I need to be able to add some binaries into my project without them being processed.

**To Reproduce**
I put the binaries in the `public` directory, then tried to specify their locations via `__dirname + "/binary-name.exe"`

**Expected behavior**
The EXEs should've been copied over to `dist_electron` so that I can actually call them.

**Additional context**
I honestly don't know whether it's a bug or a feature request.
What I do know is that I need it working in order for my application to work.

**Comment by nklayman** [comment]
Files in the public folder definitely should be copied, but you will need to use `__static` instead of `__dirname` to access where they are copied.

However, they will be packaged into the `app.asar` archive, and can't be executed from there. What you should do is create a new folder in the root of your app, let's call it `binaries`. Put your binaries inside `binaries`, then update your `vue.config.js` like so:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        extraResources: ['./binaries/**']
      }
    }
  }
}
```
The binaries will then be copied into `(unpacked app dir)/resources/binaries`. This folder can be accessed with `path.join(__static, '../binaries')` in both build and serve.
