### ISSUE TITLE
html hash anchor did not work with app://./

### ISSUE THREAD

**Issue by banxi1988** [nklayman/vue-cli-plugin-electron-builder#113]
**Describe the bug**
html hash anchor did not work

**To Reproduce**
1) add some html hash anchor link
2) click anchor link
3) get error

```
GET app://./ net::ERR_NOT_implemented app://./#chapter1
```

**Expected behavior**
jump to target anchor

**Environment (please complete the following information):**
 - OS and version: (mac,windows)
 - Node version:  v8.9.3
 - npm version: N/A
 - yarn version (if used): 1.10.1
 - vue-cli-plugin-electron-builder version : 1.0.0-rc.3
 - other vue plugins used:  N/A
 - custom config for vcp-electron-builder: N/A
 - (if possible) link to your repo: N/A

**Comment by nklayman** [comment]
I think this is fixed in the latest commit. This will be part of the next release. If you want to use it now, you will need to download this plugin from the github repo, to do so:
1. in `package.json`, set `vue-cli-plugin-electron-builder` to `nklayman/vue-cli-plugin-electron-builder`
2. run `yarn install` or `npm install`
3. now, remove the `<% if (BASE_URL === './') { %><base href="app://./" /><% } %>` from `public/index.html`
4. you should be good to go, build your app and see if it works!
