### ISSUE TITLE
Apple Silicon, Electron 11 compatibility

### ISSUE THREAD

**Issue by alectrocute** [nklayman/vue-cli-plugin-electron-builder#1136]
**Is your feature request related to a problem? Please describe.**

To build for Apple’s newly released ARM platform, I’m under the impression we’ll need Electron 11. Without this, end users on said hardware cannot open distributed Electron apps.

**Describe the solution you'd like**

If Electron 11 isn’t currently supported, I would love to see it supported so we can migrate and support flagship Apple hardware in production.

**Describe alternatives you've considered**

Alternative build flow/packager, but would like to avoid that.

**Additional context**

https://github.com/electron-userland/electron-builder/issues/5392

https://github.com/electron-userland/electron-builder/issues/5397

**Comment by nklayman** [comment]
This plugin supports Electron 11 just fine afaik, I just haven't added it as an option to the generator because Spectron (Electron's testing framework) is broken for versions 10+. Usually, Spectron is updated soon after the Electron release, but it seems like they are really slacking this time around, see https://github.com/electron-userland/spectron/issues/720. I may just have to add it to the generator anyway with a note about the lack of testing support.

As for Apple Silicon support, this plugin should support it as soon as electron-builder and electron do. I won't be getting an apple silicon device so I won't be able to test it myself to confirm, however.
