### ISSUE TITLE
About Axios not working properly

### ISSUE THREAD

**Issue by jiumengs** [nklayman/vue-cli-plugin-electron-builder#1236]
**Describe the bug**

**To Reproduce**
When sending a request using Axios,
axios.defaults.adapter = require("axios/lib/adapters/http");
The request is still sent by the browser, so the header append fails and is intercepted by Electron

**Expected behavior**
Use Axios to send requests with a Cookie in the header
Enables Axios statements to take effect
axios.defaults.adapter = require("axios/lib/adapters/http");

**Screenshots**

**Environment (please complete the following information):**
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 
 - terminal output from running `vue info`:
![1 (1)](https://user-images.githubusercontent.com/39983417/107272372-81ecce80-6a45-11eb-8377-363edcf6f6c0.png)
![2](https://user-images.githubusercontent.com/39983417/107272378-84e7bf00-6a45-11eb-87f3-c7eb888d721a.png)

**Additional context**

**Comment by jiumengs** [comment]
My current solution is to modify the Axios source code

**Comment by nklayman** [comment]
This issue appears to be related to Axios/Electron in general, see https://github.com/axios/axios/issues/1231. Since this issue is unrelated to this plugin, I'm closing it. I suggest sending requests from the main process using a library like [Got](https://www.npmjs.com/package/got), it should let you set any headers you want.
