### ISSUE TITLE
Cannot find module - app.asar

### ISSUE THREAD

**Issue by welcome14** [nklayman/vue-cli-plugin-electron-builder#1381]
Hi,
I have this error after build my app.
`index.html#/:1 Uncaught Error: Cannot find module 'C:\......\dist_electron\win-unpacked\resources\app.asar/../src/model/myfile.jsc'
Require stack:
- C:\........\dist_electron\win-unpacked\resources\app.asar\background.js`

this is the code in App.vue
`const electron = require('electron');
const model = electron.remote.require(electron.remote.app.getAppPath() + "/../src/model/myfile.jsc");
export default {....`

if i run in serve mode, it work! 
if i run a build version, i have this issue... why ?

i use bytenode for protect the source code.

thanks

**Comment by nklayman** [comment]
That won't work in build because the `src` directory isn't copied into the executable. You should put the jsc file in the public dir and use `__static` to get the path to that dir, it will work in both build and dev. See [handling static assets](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#handling-static-assets) for more details.

**Comment by welcome14** [comment]
I have put the file into public directory, but  it not work!
Cannot find module 'C:\Users\........\dist_electron\win-unpacked\resources\app.asar\myfile.jsc'

i have modify the app.vue in ... 
`const model = require(path.join(__static , "myfile.jsc"))`

How can i resolve ? 
The app not work in dev modem, not even in build, now.

**Comment by nklayman** [comment]
Please share your project repository, I can't help unless I can reproduce the issue.

**Comment by welcome14** [comment]
i have resolve with
`const model = require('electron').remote.require(path.join(__static , "/myfile.jsc"));`
in app.vue file...
