### ISSUE TITLE
Broken Build - 2.0.0

### ISSUE THREAD

**Issue by quanc** [nklayman/vue-cli-plugin-electron-builder#1424]
**Describe the bug**
A few hours ago, I started to get the following error from electron-builder packaged with vue-cli-plugin-electron-builder when running "npm install":

Error: Cannot find module 'fs/promises'

I suspect this is because a new version of electron-builder was published a few hours ago. A fix (or electron-builder downgrade) would be great! As a workaround, I downgraded my version of vue-cli-plugin-electron-builder.

**Comment by laurensiusadi** [comment]
Related https://github.com/electron-userland/electron-builder/issues/5953

**Comment by nklayman** [comment]
You can downgrade electron-builder with [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/), see https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/707#issuecomment-613131820 for more details. Seems like updating to Node v14 or greater fixes the issue as well. Since I can't really do anything about this because it's on the electron-builder side of things, I'll close this.
