### ISSUE TITLE
build success, but node_modules is empty

### ISSUE THREAD

**Issue by liuchang2978** [nklayman/vue-cli-plugin-electron-builder#1522]
I have build my app successfully, but in the file "dist_electron/bundled/package.json", the "dependencies": {} is empty, and the app can`t find node moudules.

**Comment by nklayman** [comment]
That is intentional. Since all the production dependecies are bundled with webpack, there is no need for them to be in the distributed application. To force them to not be bundled and to be included in the distribution, add them to the `externals` config array. See the [native modules guide](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) for more details.
