### ISSUE TITLE
Can we not use the webpack on main process?

### ISSUE THREAD

**Issue by Bananamilk452** [nklayman/vue-cli-plugin-electron-builder#1594]
**Is your feature request related to a problem? Please describe.**
There is always a problem when I use native modules or especially child_process.fork. Initially, Electron is a library that works in node, so I hope there will be an option not to use webpacks.

P.S. The reason why we are pursuing this method is that whenever this happens, the solutions are different and complicated, causing a headache.

**Describe the solution you'd like**
I hope there will be a version that doesn't use a web pack or an option to do so.

**Comment by nklayman** [comment]
Sorry for the delayed response, had to take a break from open source to focus on school.

You can follow https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/98#issuecomment-426370253, even though it's an old answer I think most of the instructions still apply and it will still work (if a step says to remove something that isn't there just skip it). I'd highly recommend configuring your [externals](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules) instead of disable webpack entirely, but if that doesn't work for you then give the linked comment a try. Let me know if you run into any issues.
