### ISSUE TITLE
Aligning to the latest version of eletron-builder.

### ISSUE THREAD

**Issue by ahmedalami** [nklayman/vue-cli-plugin-electron-builder#1613]
When building for windows using the latest version of the plugin, the generated uninstaller is considered containing a trojan. This is due to the version of the electron builder.

[Aligning to the latest version](https://github.com/ashishBharadwaj/flawesome/issues/17) electron-builder will fix this issue.

Can you please align the latest version of electron-builder : 22.14.5 ?

Thank you in advance.

**Comment by zzxxiinn** [comment]
any progress?

**Comment by klren0312** [comment]
https://github.com/nklayman/vue-cli-plugin-electron-builder/pull/1600

**Comment by zzxxiinn** [comment]
I find a way to walkaound this issue, just lock sub-deps version in your `package.json` file:
```json
{
  ...
  "resolutions": {
    "app-builder-lib": "^22.14.10",
    "electron-builder": "^22.14.5"
  }
}
```

**Comment by skuIIs** [comment]
This also fixed an issue where none of the `ready-to-show`, `did-finish-load`, or `dom-ready` events fired. Now the `ready-to-show` event fires now.

**Comment by nklayman** [comment]
If you are using yarn, the above solution will work for you. Otherwise, you might be able to delete part of your `package-lock.json` to make npm refetch electron-builder. If not, just nuke the whole file and reinstall. By default, this plugin will use the latest electron-builder version, it's just that the old  one is stuck in your lockfile.
