### ISSUE TITLE
How to Build Electron App Another Platform like (Linux, Mac)

### ISSUE THREAD

**Issue by jeevan15498** [nklayman/vue-cli-plugin-electron-builder#166]
This command creates the .exe of the window
```
npm run electron:build
```
How to build project for the another OS.

```
"build": {
    "productName": "demo",
    "appId": "demo.id.jeevan",
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/icon.ico"
    },
    "linux": {
      "icon": "build/icons"
    }
  },
```

**Comment by KocaHocTpa** [comment]
+1. 
My OS: Windows 10.
I need to compile my applications for Linux deb, But I get an error. 


 INFO  Building app with electron-builder:
  • electron-builder version=20.38.4

  • no native production dependencies

  • packaging       platform=linux arch=x64 electron=3.0.10 appOutDir=dist_electron\linux-unpacked

  •
scheduling remote build target=deb arch=x64

  • cannot get, wait          attempt=0 error=Get https://service.electron.build/find-build-agent?no-cache=1e243fk: dial tcp 51.38.69.239:443: connectex: No connection could be made because the target machine actively refused it. waitTime=2

  • cannot get, wait          attempt=1 error=Get https://service.electron.build/find-build-agent?no-cache=1e243fk: dial tcp 51.38.69.239:443: connectex: No connection could be made because the target machine actively refused it. waitTime=4

  • cannot get, wait          attempt=2 error=Get https://service.electron.build/find-build-agent?no-cache=1e243fk: dial tcp 51.38.69.239:443: connectex: No connection could be made because the target machine actively refused it. waitTime=6

  ⨯ Get https://service.electron.build/find-build-agent?no-cache=1e243fk: dial tcp 51.38.69.239:443: connectex: No connection could be made because the target machine actively refused it.


 ERROR  Error: c:\OSPanel\domains\clientCard\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1

**Comment by nklayman** [comment]
@jeevan15498 pass `--linux` when calling `electron:build` (`npm run electron:build --linux`) to build for linux. You can only build for MacOS on a Mac.

@KocaHocTpa you can only build a `.deb` from a computer running linux. It is trying to upload your app and have it build on a cloud server running linux. You can report it failing on [electron-builder's repository](https://github.com/electron-userland/electron-builder) (that is what handles the native build phase). I suggest looking into the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about). It will allow you to run a linux command line inside of Windows with access to all of your files. You can use that to build the `.deb`.
