### ISSUE TITLE
Use V3 Alpha

### ISSUE THREAD

**Issue by StrangerGithuber** [nklayman/vue-cli-plugin-electron-builder#1822]
Hello
Can I use to production or I should wait more to be stable version?
I mean for stability or this project is abandoned?

Thank you in advance the answers.

**Comment by MatthijsBurgh** [comment]
This project is not abandoned. The full transition to Vue V3, does require a lot of other changes. So that is a complex process. Which does take a lot of time.
V3 is an alpha, so it is an alpha. Though this project is just a plugin to generate an executable. So when the executable is generated, The work of this plugin is done, and the stability is based on your application.

**Comment by StrangerGithuber** [comment]
Oh ok. Now I understand. I just asked because a YouTuber said the Vue 2 will be not supported in the near future and started to think whoopsie. Now I understand. Thank you again for the answer.
