### ISSUE TITLE
Are .env and .env.local files placed directly under the project root packed in the built product file?

### ISSUE THREAD

**Issue by kaede-labs-jp** [nklayman/vue-cli-plugin-electron-builder#1936]
Are .env and .env.local files placed directly under the project root packed in the built product file?

**Comment by MatthijsBurgh** [comment]
I don't know

**Comment by kaede-labs-jp** [comment]
Is this also under the jurisdiction of electron-builder?

**Comment by MatthijsBurgh** [comment]
Yes, most features of `electron-builder` can just be configured in the `vue.config.js` (see https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder). This project just forward this configuration to the builder. I doesn't do anything to it. So when something is not working, the issue is in your configuration or in the builder.

For this issue, I have found the following link: https://stackoverflow.com/questions/63001117/how-to-read-from-env-file-in-electron-builder-yaml-config-file.
To me it seems the ENV file variables can be used in a config file/object. This project provides a configuration object to the builder based on the config in `vue.config.js`. So you should be able to use the values from the ENV file in `vue.config.js`.
Based on the same assumption I THINK the ENV file is not packed, as it is only used in configuring the build.

**Comment by kaede-labs-jp** [comment]
Thank you!
