### ISSUE TITLE
electron-vue

### ISSUE THREAD

**Issue by tiptronic** [nklayman/vue-cli-plugin-electron-builder#232]
I hope it is okay to ask this question here:
What is the benefit using a Vue-CLI plugin over a separated boilerplate like e.g.:

https://github.com/SimulatedGREG/electron-vue/

Sorry if the question is quite basic, but I am just about getting my head around it 😉

**Comment by RacerDelux** [comment]
They are different approaches. SimulatedGREG/electron-vue/ dos not use vue cli 3 though. It is actually out of date in many areas.

**Comment by tiptronic** [comment]
@RacerDelux Thanks for the info!
Is it possible to setup a project which includes an own build-process, e.g. created by framework7-cli?
In the documentation I couldn't find any info how this would work...

**Comment by RacerDelux** [comment]
What do you mean by own build process? Do you mean build configs for electron?

**Comment by tiptronic** [comment]
No - sorry for being unclear!
If I create a project using e.g. framework7-cli, it creates a webpack-project which needs to get compiled before run/serve. How would I include such a project

**Comment by RacerDelux** [comment]
Is this what you are after? You can configure webpack and pass those configs through.
https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#table-of-contents

**Comment by tiptronic** [comment]
Not sure, if I'm after that 😊- but reads promising... I'll give that a shot. 
Thanks for your input!

**Comment by nklayman** [comment]
Most of the advantages of Vue CLI Plugin Electron Builder come from Vue CLI 3. Vue CLI 3 uses a plugin-based system for additions to your app. This means that you can add features to your app automatically. There are plugins for typescript, e2e and unit testing, linting, Quasar, Vuetify, etc... All you need to do is run `vue add [plugin]`. With a Vue CLI 2 template, you have to add extra features manually. Since webpack configuration is handled by plugins, it doesn't add files to your app. With a Vue CLI 2 template, you can't update anything. With Vue CLI 3 you can upgrade the plugins, which then gives you the latest webpack config. Vue CLI 3 also uses newer versions of dependencies (such as babel). Vue CLI 3 also has a UI, which makes it easier for less experienced developers to manage their project. Vue CLI Plugin Electron Builder will use Webpack to bundle your non-native dependencies (unlike electron-vue), which will increase runtime performance and reduce bundle size. Electron Vue's development has nearly stopped, with the last commit in October. Vue CLI 3 is the way to go now.

**Comment by nklayman** [comment]
You wouldn't be able to use this plugin with a framework-7 cli project.
