### ISSUE TITLE
ElectronBuilder and SerialPort

### ISSUE THREAD

**Issue by feeh27** [nklayman/vue-cli-plugin-electron-builder#427]
**Describe the bug**

I can't set data from a native module declared as external to a vue component property.

**To Reproduce**

I'm using a native module called serialport, for it to work it was necessary to declare as externals in the vue.config.js:

```ts
module.exports = {
    pluginOptions: {
        electronBuilder: {
            externals: ['serialport']
        }
    }
};
```

I followed these steps according to the electron-builder guidelines and can be found at this link:
https://github.com/nklayman/vue-cli-plugin-electron-builder/blob/master/docs/guide/guide.md#native-modules-

SerialPort has a function to list the available serial ports and it returns a promise, I can print these ports on the console, but I can't save them to a Vue component property, I believe it is because it is an external module compared to webpack.

Component code:

```vue
<template>
    <div>
        <div v-for="(port, index) in ports.length" :key="port + index">
            <div :id="'port' + index">Port: {‌{ port }}</div>
        </div>
    </div>
</template>

<script>
export default{
    name: 'SerialComm',
    data: () => ({
        ports: [],
    }),
    created() {
        SerialPort.list().then((ports) => {
            for (let i = 0; i < ports.length; i++) {
                console.log('Port', i, ports[i].comName)
                this.ports.push(ports[i].comName);
            }
            console.log('Promise this.ports', this.ports);
        });
        console.log('Created this.ports', this.ports);
    }
};
</script>
```
Console output:

![image](https://user-images.githubusercontent.com/13547485/63544535-cf951480-c4fb-11e9-89c6-b13bd3b84c12.png)

Browser output:

![image](https://user-images.githubusercontent.com/13547485/63544675-1551dd00-c4fc-11e9-9e9e-68627a307f3a.png)

**Expected behavior**

In the browser output, it printed "Port: 1" and "Port: 2", where "Port:" is the text passed and the values "1" and "2" the value of the interpolated port property, it looks like it is printing the array index value + 1 instead of "COM4" and "COM19" as in console.

**Environment (please complete the following information):**
 - OS and version: Windows 10
 - node version: v10.16.2
 - npm version: 6.9.0
 - yarn version (if used): Not used
 - vue-cli-plugin-electron-builder version : 1.4.0
 - electron version: 5.0.10
 - other vue plugins used: serialport (7.1.5)
 - custom config for vcp-electron-builder: The standard was used
 - (if possible) link to your repo: Project has no repository yet

**Additional context**

This same module has other methods, but you need to create an object and from there everything works perfectly, as in the code below:

```ts
const SerialPort = require('serialport');
const Readline = require('@serialport/parser-readline');
const portName = 'COM4';
 
const port = new SerialPort(portName, { baudRate: 115200 });
const parser = port.pipe(new Readline({ delimiter: '\r\n' }));
 
port.on('open', () => {
    console.log('Serial port open');
    const msg = 'First Message';
    port.write(msg, function(err) {
        if (err) console.log('Error on write: ', err.message);
        else console.log('Message written: ', msg);
    });
});
port.on('error', (err) => { console.log('Error: ', error.message); });
parser.on('data', (data) => { console.log('Serial:', data); });
```

Console output:

![image](https://user-images.githubusercontent.com/13547485/63545986-0c163f80-c4ff-11e9-9fe0-d77c899332f2.png)

I have other components that have a promise, a non-standard vue module that are working, and the only difference between them is the declaration of externals in the vue.config.js file as stated earlier, it seems that this snippet of code is running outside the instance of Vue.

Does anyone know how I could solve this problem?

**Comment by nklayman** [comment]
This is an issue with electron-builder's `install-app-deps` function. You will have to use [electron-rebuild](https://github.com/electron/electron-rebuild) instead. To do this, install with `yarn add -D electron-rebuild` (or `npm i -D electron-rebuild`). Then, update your `package.json`:

```diff
{
...
  "scripts": {
...
-    "postinstall": "electron-builder install-app-deps",
-    "postuninstall": "electron-builder install-app-deps"
+    "postinstall": "electron-rebuild",
+    "postuninstall": "electron-rebuild"
  },
...
}
```

Now, electron-rebuild will be used to build native modules after running yarn or npm.

Set our `vue.config.js` to:
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['serialport'],
      builderOptions: {
        npmRebuild: false
      }
    }
  }
}

```

The `npmRebuild` options tells electron-builder not to build native deps when building your app, otherwise it will overwrite the proper one built with electron-rebuild.

If you are building for platforms other than the host machine, you will need to tell electron-rebuild to build your native deps for those targets as well, see [their cli options](https://github.com/electron/electron-rebuild#cli-arguments) for instructions.

I will be opening an issue on electron-builder's repo so that this issue can hopefully be fixed. Thanks for reporting the issue!

**Comment by nklayman** [comment]
Actually, it looks like you weren't having the issue I was having, my bad. I got a different issue when trying to setup serialport that I assumed was your issue. I can now replicate your actual issue, and I will try to find a solution.

**Comment by nklayman** [comment]
I found your issue! You were using `v-for="(port, index) in ports.length"`, which would iterate over the length of the array, instead of the array itself. Replace this with `v-for="(port, index) in ports"`.

As a side note, your code snippet had one of the most insane issues I have ever encountered. For some reason, the first `{` in `{{ port }}` wasn't actually a `{`. It was some kind of weird character that looked exactly like a `{` but would make it so that `{{ port }}` was displayed in the rendered app. Wow.
![image](https://user-images.githubusercontent.com/12448243/63553395-16c8d880-c4ef-11e9-8fb0-30f47bb45352.png)
![image](https://user-images.githubusercontent.com/12448243/63553403-1f211380-c4ef-11e9-8b93-d8cd8c558103.png)

**Comment by nklayman** [comment]
A zero-width non-joiner? what kind of wizadry is this?
![image](https://user-images.githubusercontent.com/12448243/63553633-e7ff3200-c4ef-11e9-967c-7ffbc4db4307.png)

Apparently this was placed after the `{`, causing it to be ignored by Vue. You could really confuse people with this. I might use this to fake the word count on some essays :wink:.

**Comment by feeh27** [comment]
> I found your issue! You were using `v-for="(port, index) in ports.length"`, which would iterate over the length of the array, instead of the array itself. Replace this with `v-for="(port, index) in ports"`.
> 
> As a side note, your code snippet had one of the most insane issues I have ever encountered. For some reason, the first `{` in `{{ port }}` wasn't actually a `{`. It was some kind of weird character that looked exactly like a `{` but would make it so that `{{ port }}` was displayed in the rendered app. Wow.
> ![image](https://user-images.githubusercontent.com/12448243/63553395-16c8d880-c4ef-11e9-8fb0-30f47bb45352.png)
> ![image](https://user-images.githubusercontent.com/12448243/63553403-1f211380-c4ef-11e9-8b93-d8cd8c558103.png)

That really was the problem, thank you so much for your help.

**Comment by focussing** [comment]
How did you get so far? 
I am getting all kinds of errors which according some posts require a rebuild... At least your serial port is responding...
Maybe you can help me?

**Comment by focussing** [comment]
Found my problem; after installing the Xcode command line tools it worked...
Thanks!

**Comment by ana-marcia** [comment]
@focussing maybe you can help me, my serialport does not work, going through the same problem that you had

**Comment by focussing** [comment]
@ana-marcia it's already a while ago, what I did was to install the Xcode command line tools (macOS).
Hope that helps :)
