### ISSUE TITLE
cannot run express server in separate process

### ISSUE THREAD

**Issue by king-d-dev** [nklayman/vue-cli-plugin-electron-builder#442]
**Describe the bug**
i want to be able to use child_process.fork() to create an express server in a separate process, which is okay during development mode but keeps giving me this error, " Cannot find module 'express'"

**To Reproduce**

**Expected behavior**
Should be able to spawn the express server in a separate process just as it does in development mode

**Screenshots**
![Screenshot (298)](https://user-images.githubusercontent.com/36765257/63772852-d373be80-c88e-11e9-8fbf-1471a8dc5c20.png)

**Comment by king-alpha** [comment]
The repo exists as private at the moment so i added u as a collaborator, here is the invite link 
https://github.com/king-alpha/share/invitations

**Comment by nklayman** [comment]
Your repository works fine for me. Please try reinstalling deps on your repo  (`rm -r node_modules && yarn`). If that still fails, try this repo: https://github.com/nklayman/electron-express-test.

**Comment by king-alpha** [comment]
i have found what the issue is, i think my explanation might be a bit lengthy but its worth our time and effort.
So after trying out the link u shared in this thread i realized that the issue is that wen electron builder runs, you can either ask for a portable build of your app or an installer build of your app, with the portable build, everything works normal without my server running in a separate process crashing , but with the installer build, trying to run the server in a separate process crashes with the error in the screenshot i used to create this issue.

**Comment by nklayman** [comment]
Did you try reinstalling deps?

**Comment by king-alpha** [comment]
Yes please

**Comment by nklayman** [comment]
Try getting rid of the `extraResources` option in your electron builder config.

**Comment by king-alpha** [comment]
I actually did that too, can you pls try and generate the installer build on your machine to see if you would also encounter similar issues as I did too, if probably its am issue with my desktop or something

**Comment by enbermudas** [comment]
How can i check if the express server is actually running on my development environment?

**Comment by nklayman** [comment]
Try using an app like [insomnia](https://insomnia.rest) to make requests to the server.
