### ISSUE TITLE
Unable to launch electron app in linux

### ISSUE THREAD

**Issue by juancampuzano** [nklayman/vue-cli-plugin-electron-builder#580]
**Describe the bug**
I am trying to launch electron app using  `npm run electron:serve` in linux but is not working. But in Winodows and Mac is working. 

**To Reproduce**

run `npm run electron:serve` 

**Expected behavior**
Launching Electron  works.

**Screenshots**
![Screen Shot 2019-12-06 at 2 41 13 PM](https://user-images.githubusercontent.com/52759609/70351243-81035000-1836-11ea-8b62-96b4ce1cdc9a.png)
 It never launch the app on linux.

**Environment (please complete the following information):**
 - OS and version: Kali GNU/Linux  and version: 2019.3
 - node version: v12.13.1
 - npm version: 6.12.1
 - yarn version (if used):  
 - vue-cli-plugin-electron-builder version :  1.4.3 
 - electron version:  5.0.12
 - other vue plugins used: 
 - custom config for vcp-electron-builder:  
 - (if possible) link to your repo:

**Comment by nklayman** [comment]
Try `rm -r node_modules && npm i`, and then running again.

If that doesn't work, try running `sudo sysctl -w kernel.unprivileged_userns_clone=1` and then launching electron. This will solve the sandboxing issue that occurs on linux with chromium. You can see more details [here](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) (for puppeteer but solutions work on electron as well).

**Comment by juancampuzano** [comment]
I'm sorry to say that none of the two ways worked for me...Also restart the computer without any results.

**Comment by nklayman** [comment]
Try deleting electron cache (`~/.cache/electron`) and reinstalling deps. Not sure what else could be wrong, I use Linux as my daily driver without issue.

**Comment by ugudango** [comment]
I have the exact same problem. I tried what you listed there, @nklayman, but nothing worked.
I also tried making an entire new project with Vue CLI and install the plugin, yet that achieved the same result.
I am currently running Manjaro 5.1 Gnome.

**Comment by juancampuzano** [comment]
I already try doing all the steps you mention, without any result, can it be a problem with the Node.js version?

**Comment by AlexSHoffman** [comment]
@juancampuzano try updating Electron to `7.1.7` (the latest version). Might be a bug with Chromium.

**Comment by nklayman** [comment]
Please try @AlexSHoffman's suggestion.

**Comment by tomelic** [comment]
I am having the same issue, can we re-open?

**Comment by tomelic** [comment]
1. changed electron version to 7.1.7
2. sudo rm -rf ~/.cache/electron
3. sudo sysctl -w kernel.unprivileged_userns_clone=1
4. rm -r node_modules && npm i

same environment as OP (tried both Kali Linux and Ubuntu 18.04), same behavior as shown in OP's picture.

**Comment by willermorais** [comment]
My distro is Debian with the same problem. I installed the chromium and ran the command `sudo sysctl -w kernel.unprivileged_userns_clone=1` suggested by @nklayman. Worked, thank you!

**Comment by Estradiaz** [comment]
I had to add yarn

**Comment by hatsantos** [comment]
I don't use Linux daily (Windows Dev) but now I need to build and app for Linux using Electron.

I am facing a similar issue... The app works when running only the "webapp", the build is done successfully but when trying to open the app nothing happens, not even the splash screen appears on the screen.

Since I'm not a regular Linux user, can I ask what exactly does the command:

`sudo sysctl -w kernel.unprivileged_userns_clone=1`

How can I rollback the previous command? Did not tested the command (do not want to break my Linux installation or anything...)

Do my app users also need to do this?

I'm using a virtual machine (VirtuaBox) with Ubuntu 20.10 to build and test the app.

My Electron version is 10.2.0.

**Comment by nklayman** [comment]
@hatsantos see [this link](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox) for more details on the purpose of that command. The page is for puppeteer but the issue is the exact same as Electron as both use Chromium, which is causing the issue.
