### ISSUE TITLE
Not able to build on Raspberry Pi

### ISSUE THREAD

**Issue by Nais0ne** [nklayman/vue-cli-plugin-electron-builder#581]
**Describe the bug**
When I try to build on my raspberry PI with `npm run electron:build` I get the error "unsupported arch arm". I already looked up the docs but can't seem to find any option/parameter to pass and make it work

**To Reproduce**
build on raspberry Pi

**Expected behavior**
That it works out of the box or the ability of passing a parameter to make it work

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Raspian 10 (debian buster)
 - node version: 10.15.2
 - npm version: 5.8.0
 - yarn version (if used): 
 - vue-cli-plugin-electron-builder version : 1.4.3
 - electron version: 6.0.0
 - other vue plugins used: none
 - custom config for vcp-electron-builder: none
 - (if possible) link to your repo: 

**Additional context**

**Comment by nklayman** [comment]
This error is caused by electron builder, not this plugin. Try passing the `--arm64` or `--armv7l` arguments to the command (`npm run electron:build -- --arm64`, don't skip extra `--`). A [similar issue](https://github.com/electron-userland/electron-builder/issues/4279) exists on the electron-builder repo, so if these solutions don't work you can add a comment to that thread.

**Comment by mchev** [comment]
To work properly in RPI4 raspian i used : 
`npm run electron:build -- --linux --armv7l --dir`
I hope this helps those who were stuck for a long time like me

**Comment by godprogrammer3** [comment]
> To work properly in RPI4 raspian i used : `npm run electron:build -- --linux --armv7l --dir` I hope this helps those who were stuck for a long time like me

It worked for we thanks!
