### ISSUE TITLE
Stuck on Lauching Electron after updating to 2.0.0

### ISSUE THREAD

**Issue by filipcieminski** [nklayman/vue-cli-plugin-electron-builder#649]
After creating a fresh project from vue-cli and adding electron buildier, app is not working. Just stucking on "Launching Electron..." everything works fine when I'm downgrading vue-cli-plugin-electron-builder to version 1.4.4. I have tried to clear cache, delete node modules etc. No success.

Also, where I can find vue.config.js? Is that the file I should create myself and place it in root folder/scr folder/somewhere? How should I link it in my background.js to make nodeIntegration works? Documentation doesnt specify that.

 - OS and version: Win 10
 - node version: 13.3
 - npm version: 6.12
 - vue-cli-plugin-electron-builder version : 2.0.0-beta
 - electron version: 6.0

**Comment by syslao** [comment]
same thing

**Comment by ycharron-cstj** [comment]
Same here with 2.0.0-beta.2

**Comment by senritsu** [comment]
Same here, did i seriously hit the exact time a breaking issue appeared when trying out this thing for the first time right now ? 😅

**Comment by Rotinx** [comment]
Yep, I've got the same issue. 
![image](https://user-images.githubusercontent.com/39930952/74063158-befa3b80-4a54-11ea-8249-0133ca14d7cb.png)

**Comment by ycharron-cstj** [comment]
> Same here, did i seriously hit the exact time a breaking issue appeared when trying out this thing for the first time right now ? 😅

Me too was trying this for the first time this morning.

**Comment by Rotinx** [comment]
Found a temp fix.

Within the `package.json` file change vue-cli-plugin-electron-builder's verison to `^1.4.4`
`"vue-cli-plugin-electron-builder": "^1.4.4",`

and within the `background.js/.ts` file change 
`nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION `
to
`nodeIntegration: true`

then `npm install` to update dependences and then `npm run electron:serve`

**Comment by nklayman** [comment]
Whoops, did not mean to publish the beta under the latest tag. Really wish yarn would give me a warning when I publish `x.x.x-beta.x` under `latest`. I just published v1.4.5 which will override the accidental publish, and v1.0.0-beta.3 is published with the beta tag.

Anyways, there is an [upgrading guide](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) available if you do want to upgrade to the v2.0 beta. 

@filipcieminski the `vue.config.js` is just a file in the root of your vue cli project, see [the vue cli docs](https://cli.vuejs.org/config/#vue-config-js) for more details.

Sorry guys, didn't mean to do that, and thanks for letting me know I goofed so that I could fix it.
