### ISSUE TITLE
When will the official version of 2.0 be released?

### ISSUE THREAD

**Issue by Hunlongyu** [nklayman/vue-cli-plugin-electron-builder#705]
1. When will the official version of 2.0 be released?

2. How to use the current beta version? 2.0.0-beta.6

**Comment by nklayman** [comment]
I can't make it stable until Vue CLI drops support for node 8 because a required dependency for v2.0 does not support node 8. You can use the beta in a new project with `yarn add -D vue-cli-plugin-electron-builder && vue invoke electron-builder`, or upgrade an existing project by following the migration guide in the [release announcement](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0).
