### ISSUE TITLE
Support --modern flag

### ISSUE THREAD

**Issue by erguotou520** [nklayman/vue-cli-plugin-electron-builder#71]
**Is your feature request related to a problem? Please describe.**
Need a way to switch `--modern` flag as it will not load the js script when not use registed protocol like 
 `app://./`.

**Describe the solution you'd like**
Maybe `npm run build:electron --modern false`?

**Comment by nklayman** [comment]
Why can't you just use the `app` protocol? It is created and used by default. I can add a switch if you need, im just wondering why it doesn't work.

**Comment by erguotou520** [comment]
It works, but I think it will throw error when there're multi apps that registered the same `app` protocol.

**Comment by nklayman** [comment]
This feature will be available in the next release. To use it now, set vcp-electron-builder's version to `nklayman/vue-cli-plugin-electron-builder` to install from the github repo.

**Comment by nklayman** [comment]
the command is `--legacy`.

**Comment by nklayman** [comment]
1.0.0-rc.3 has been released, along with this feature/fix. You may now use that as vcp-electron-builder's version instead of the github repo (recommended).1.0.0-rc.3 has been released, along with this feature/fix. You may now use that as vcp-electron-builder's version instead of the github repo (recommended).
