### ISSUE TITLE
Electron 6.0.0 need 8.0.0 spectron dependence

### ISSUE THREAD

**Issue by ajmasia** [nklayman/vue-cli-plugin-electron-builder#719]
**Describe the bug**
When use electron 6.0.0 version and run some test with spectron, I get and error related with Chrome version: `Chrome version must be between 70 and 73`

**To Reproduce**
Run the electron example test with elecctron 6.0.0

**Expected behavior**
The test should work fine without errors.

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: MacOS 10.15.4
 - node version: 12.16.1
 - npm version:
 - yarn version (if used): 1.22.4
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 6.0.0
 - other vue plugins used: Vuetify, Router, Vuex
 - custom config for vcp-electron-builder: 
 - (if possible) link to your repo: 

**Additional context**
Currently the plugin use spectron 7.0.0 and according to the [version map](https://github.com/electron-userland/spectron) you should use version 8.0.0

I have seen that version 2 can solve this problem. For when a stable version?
Thanks for maintaining this repository :-)

**Comment by nklayman** [comment]
The [2.0 beta](https://github.com/nklayman/vue-cli-plugin-electron-builder/releases/tag/v2.0.0-beta.0) allows you to specify the spectron version in your `package.json`. Otherwise, you can use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to change to the proper spectron version.
