### ISSUE TITLE
Not compatible with CopywebpackPlugin

### ISSUE THREAD

**Issue by cavencj** [nklayman/vue-cli-plugin-electron-builder#749]
When I use the CopywebpackPlugin to copy the file, I have set the target directory, but when use  **electron:build** script , the file to the root directory and add node_modules directory. My configuration is as follows:

``` js
const path = require('path')

const CopywebpackPlugin = require('copy-webpack-plugin')
const dvgis = './node_modules/@dvgis'

let resolve = dir => {
  return path.resolve(__dirname, dir)
}

module.exports = {
  publicPath: process.env.NODE_ENV === 'production' ? '/' : '/',
  productionSourceMap: false,
  configureWebpack: {
    module: {
      unknownContextCritical: false
    },
    performance: {
      hints: false
    }
  },
  chainWebpack: config => {
    config.resolve.extensions.add('.js').add('.vue')
    config.resolve.alias.set('dvgis', path.resolve(__dirname, dvgis))
    config.plugin('copy').use(CopywebpackPlugin, [
      [
        {
          from: path.join(dvgis, 'dc-sdk/dist/resources'),
          to: 'libs/dc-sdk/resources'
        }
      ]
    ])
  }
}
```
the directory bundled didn't have the **`libs/dc-sdk/resources`** directory structure, so what else did I need to configure

**Comment by cavencj** [comment]
Now that I've added the following configuration it works, but I don't think it's a good solution
```
 pluginOptions: {
    electronBuilder: {
      chainWebpackMainProcess: config => {
        let outputDir = 'dist_electron/bundled'
        fs.removeSync(path.join(__dirname, outputDir, 'some file'))
        config.plugin('copy').use(CopywebpackPlugin, [
          [
            {
              from: path.join(dvgis, 'dc-sdk/dist/resources'),
              to: path.join(__dirname, outputDir, 'libs/dc-sdk/resources')
            }
          ]
        ])
      }
    }
  }
```

**Comment by nklayman** [comment]
If you mark `dvgis` as an external all of its `node_modules` files will be copied into the final app, so you can access them by `path.join(__dirname, 'node_modules/@dvigs/...)`:
```js
// vue.config.js
 pluginOptions: {
    electronBuilder: {
      externals: ['dvgis']
    }
  }
```

Try this and if it works please close the issue, otherwise you can try using the [electron builder file config](https://www.electron.build/configuration/contents) to copy the files, just make sure to place the configuration under [the proper pluginOptions tag](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/configuration.html#configuring-electron-builder).
