### ISSUE TITLE
Using stripe

### ISSUE THREAD

**Issue by sydney-d** [nklayman/vue-cli-plugin-electron-builder#752]
Hello,

I'm trying to use [Stripe elements](https://stripe.com/docs/stripe-js) in my vue views, but when I build the app I get this error : 
`Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/security#tls`

Indeed, from what I understand when built the app is served from `app://`.

Do you have a idea of how I could make my stripe form working within electron ?

Sorry for not respecting the issue reporting template, but this is not a really a bug report.

Thanks

**Comment by fsproru** [comment]
@sydney-d we had the same issue in our app and moved our payment to the web because Electron isn't supported by Stripe elements.

**Comment by nklayman** [comment]
What might work is to host the payment page as a regular web app, then use a [webview](https://www.electronjs.org/docs/api/webview-tag) (or iframe, browserview, or just a whole new window) that points at the url of the hosted payment page. Since that page uses https, it should work just fine with stripe and the user won't be able to tell the difference.
