### ISSUE TITLE
Stuck at electron:build

### ISSUE THREAD

**Issue by Bananamilk452** [nklayman/vue-cli-plugin-electron-builder#756]
**Describe the bug**
just stuck(stop) at Bundling render process:. no extra detail from DEBUG=*
but build,serve successfully at dev mode (yarn electron:build --development, yarn electron:serve)

**To Reproduce**
yarn install
yarn electron:build

**Expected behavior**
Successful build

**Screenshots**
![image](https://user-images.githubusercontent.com/30289254/82119459-b2a31e80-97b9-11ea-8471-512287761e70.png)

![image](https://user-images.githubusercontent.com/30289254/82119477-e0886300-97b9-11ea-8e9c-459b8ad7a8ea.png)

**Environment (please complete the following information):**
 - OS and version: Windows 10 1909
 - node version:  12.14.1
 - npm version:  6.14.2
 - yarn version (if used): 1.19.1 
 - vue-cli-plugin-electron-builder version : 1.4.6
 - electron version: 6.0.0
 - other vue plugins used: vuex, pug
 - custom config for vcp-electron-builder:  externals: ['knex', 'sqlite3'],
 - (if possible) link to your repo: repo is private, so i upload source [MEGA](https://mega.nz/file/4jZQDKQD#k9ioBD9O6BblmSuPzD67gAkVsjf2tnWtQQ3BemSUrDQ)

**Additional context**
initial project was successfully built.

**Comment by nklayman** [comment]
The error on `yarn build:electron` occurs during the renderer process build which is handled by vue cli. `yarn build` fails the same way which means the problem doesn't have to do with this plugin because it fails with a normal build as well. You can open an issue on [the vue cli repo](https://github.com/vuejs/vue-cli) instead.
