### ISSUE TITLE
[2.0 RC] Weird routing bug resulting in chrome-error://chromewebdata/

### ISSUE THREAD

**Issue by yvesh** [nklayman/vue-cli-plugin-electron-builder#806]
**Describe the bug**
Just noticed my first bug with the upcoming 2.0 version. And it's not easy to describe or replicate, because it's in the built production version only (dev, web etc. is fine).

For some more complex Vue.js router-links in the production version you get redirected to chrome-error://chromewebdata/, which results in a blank page.

What makes it even more weird is that some links are working, simple example:

Working:

/C:\Users\Administrator\AppData\Local\Programs\empoche\resources\app.asar/#/tasks?status=done

Not working (resulting in a blank page):

/C:\Users\Administrator\AppData\Local\Programs\empoche\resources\app.asar/#/tasks?project=5e36b9bd9e1e9600131c153e&amp;status=active

As you can see the "generated" links are identical (except the parameters) and it's not the count of parameters (tested that too).

```vue
<router-link :to="{path: '/tasks', query: {project: item._id, status: 'active'}}">
  //...
</router-link>
```
Any ideas?

**To Reproduce**
Probably need to create a demo app for that, maybe try some more complex router-links with at multiple query parameters.

**Expected behavior**
No Error

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: Doesn't matter, macOS, Snap, Windows are all affected
 - node version: -
 - npm version: -
 - yarn version (if used): -
 - vue-cli-plugin-electron-builder version : 2.0 RC
 - electron version: 8
 - other vue plugins used: vue-router

**Comment by nklayman** [comment]
I tried a handful of complex router links and none of them gave the error you described (on ubuntu linux). I also tried the specific error link you gave as well. If you can create a demo app that reproduces the error then I'd be happy to take a look at it and see if I can fix it, but since I can't get the error myself I don't know how to help. One guess is that your final link is too long and that is what is causing the error. Try cutting the length of the really long parameter and see if that helps.
