### ISSUE TITLE
Require file from absolute path

### ISSUE THREAD

**Issue by mpociot** [nklayman/vue-cli-plugin-electron-builder#809]
Hey,

I'm currently experimenting with a "plugin" system for one of my apps and to achieve this, I need to resolve files using absolute paths.

When I try to require those plugin files in my main process, I'm getting webpack errors like this:

> Error: Cannot find module '/Users/marcelpociot/Electron/project/extra/plugin/lib/index.js'

The file does exist though, so I guess I need to modify the webpack configuration in order to enable this?

Any hint in the right direction would be highly appreciated.

Oh and since the plugin path should be somewhat dynamic, I can't add those paths as fixed values to my webpack resolve configuration.
I was hoping to just be able to require those files using absolute paths.

**Comment by wuxiaobin1995** [comment]
you can try __static，just like this:
`
import fs from 'fs'
import path from 'path'

let fileContents = fs.readFileSync(path.join(__statics, '/someFile.txt'), 'utf8')
`

**Comment by nklayman** [comment]
If you want to require a module at runtime instead of having webpack bundle it, use `__non_webpack_require('module')`. This should allow you to dynamically import whatever you need. Just be careful though, as this is very dangerous because the js file you require will have full access to the file system and other powerful apis.
