### ISSUE TITLE
'vue-cli-plugin-electron-builder' should be listed in the project's dependencies, not devDependencies

### ISSUE THREAD

**Issue by gotnone** [nklayman/vue-cli-plugin-electron-builder#918]
**Describe the bug**
Using the airbnb eslint configuration leads to the following linting error in a fresh electron builder project.

````
Running completion hooks...error: 'electron' should be listed in the project'
s dependencies, not devDependencies (import/no-extraneous-dependencies) at src\b
ackground.js:1:46:
...
error: 'vue-cli-plugin-electron-builder' should be listed in the project's depen
dencies, not devDependencies (import/no-extraneous-dependencies) at src\backgrou
nd.js:2:32:
...
error: 'electron-devtools-installer' should be listed in the project's dependenc
ies, not devDependencies (import/no-extraneous-dependencies) at src\background.j
s:3:50:
````

**To Reproduce**
The this eslint error can be easily reproduced by performing the following steps:
````
vue create foobar
cd foobar
vue add eslint (then select airbnb configuration)
vue add electron-builder
````

**Expected behavior**
I expected the `vue add electron-builder` command to modify the eslint configuration to add:
````
"settings": {
      "import/core-modules": [
        "electron"
      ]
    }
````
I also expected the eslint configuration to be modified to silence the error for `vue-cli-plugin-electron-builder` and `electron-devtools-installer` should be listed in the project's dependencies.

Perhaps it would be enough to add a section about problems with using the airbnb style with eslint on the [common issues page](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/commonIssues.html#exceptions-in-async-functions-not-getting-logged-to-console)

**Comment by nklayman** [comment]
Here is why I install those packages to `devDependencies` over `dependencies`:
- The official [electron quickstart](https://github.com/electron/electron-quick-start/blob/master/package.json) has electron in `devDependencies`, not `dependencies`
- Vue CLI automatically installs plugins to `devDependencies` so I can't really change that without some sort of hack
- [Electron devtools installer](https://www.npmjs.com/package/electron-devtools-installer) recommends installing as a `devDependency`

Automatically configuring eslint would be pretty difficult due to the various ways it could be configured (`package.json`, json file, js file). If you make a PR that works well I will gladly accept it, but that's not something I will try to implement myself.


I could make a note about the issue on the docs, but the airbnb config is not commonly used for vue cli projects (afaik), and it seems like an easy issue to google and fix. If there are others who struggled with this issue then I will consider adding a notice.
