### ISSUE TITLE
node modules not found after build

### ISSUE THREAD

**Issue by modmoto** [nklayman/vue-cli-plugin-electron-builder#929]
Hi,

I have a vue/typescript/electron app that is missing node modules after the build is completed. Modules from node itself can be used by require, but not any other module that was installed with npm. So when i use  const `AdmZip = window.require('adm-zip'); ` I get an error, but modules like `const fs = window.require("fs"); ` work just fine. I noticed, that the node_modules folder in the dist_electron folder is empty after building, maybe this is a clue? I do not know, if this is a problem in my config, this plugin or electron-builder itself, but as I am struggling with it for some days now, I just start asking here. I also do not have much experience with electron so far, especially with building it :/

This is the repo, if you want to reproduce it:
https://github.com/w3champions/w3champions-launcher (Branch: AddLauncherStuff)

**Comment by nklayman** [comment]
By default, `require` and `import` statements are evaluated at build time and the dependencies are inlined with webpack. This works fine for most modules, but modules that make use of native components (ie `adm-zip`) don't work this way. In order to use modules like this, you'll have to [configure them as externals](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules). webpack automatically does this for builtin node modules, so that's why `fs` works.

**Comment by modmoto** [comment]
Thanks, this explanation seems to put me on the right track. Thanks a lot!
